### ISSUE TITLE
How to change color of navigation item when selected programatically 

### ISSUE THREAD

**Issue by KishanViramgama** [volsahin/bottomify-navigation-view#3]
![screenshot_1](https://user-images.githubusercontent.com/18188589/47417461-a13c9080-d795-11e8-8cb5-c936b70aaac9.png)

**Comment by volsahin** [comment]
Hello @KishanViramgama 
Thanks for informing me. Actually i realized i didn't set active colors when changed tab programmatically. So i fixed it. You can use v1.0.1.
By the way your app looks good. If you upload it to store, send the link to [cesahinvolkan@gmail.com](url) so i can show your app on readme
