### ISSUE TITLE
It's so nonsense if we don't know how to import the library

### ISSUE THREAD

**Issue by nurain150** [volsahin/bottomify-navigation-view#7]
How do we import

**Comment by volsahin** [comment]
Have you seen download section on readme page? @nurain150 
[https://github.com/volsahin/bottomify-navigation-view#download](https://github.com/volsahin/bottomify-navigation-view#download)

**Comment by nurain150** [comment]
Yeah I did it was a mistake.i thought you need import statement in activity
code
