### ISSUE TITLE
Item text is not showing if the height is set to 58dp. 

### ISSUE THREAD

**Issue by soumya247** [volsahin/bottomify-navigation-view#8]
Item text is not showing if the height is set to 58dp. Icons are occupying the entire navigation bar height with big icons with no room for text. If the height is set to "wrap_content" or atleast "65dp", the icons are remaining big but accommodates the text below it. 

The icons are adjusting to the layout height size but with no text when i reduce the layout_height from 58dp. Also, they are becoming small when i increase the padding. Then also, no text is being displayed.

Please help.

**Comment by volsahin** [comment]
Your situation depends on lots of params like image size, image padding, layout size, text size. So it is hard to say something without looking the code. The only improvement i can see that i can put vertical chaining to the bottom items. I will release new version
